export const table2 = document.createElement('div');
table2.className = 'table-responsive table2';
table2.innerHTML = `
<table class="table table-striped table-sm table2">
<thead>
    <tr>
        <th>#</th>
        <th>Header</th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td>1,001</td>
        <td>Lorem</td>
    </tr>
    <tr>
        <td>1,001</td>
        <td>Lorem</td>
    </tr>
    <tr>
        <td>1,001</td>
        <td>Lorem</td>
    </tr>
    <tr>
        <td>1,001</td>
        <td>Lorem</td>
    </tr>
    <tr>
        <td>1,001</td>
        <td>Lorem</td>
    </tr>
    <tr>
        <td>1,001</td>
        <td>Lorem</td>
    </tr><tr>
        <td>1,001</td>
        <td>Lorem</td>
    </tr>
    <tr>
        <td>1,001</td>
        <td>Lorem</td>
    </tr>
    <tr>
        <td>1,001</td>
        <td>Lorem</td>
    </tr><tr>
        <td>1,001</td>
        <td>Lorem</td>
    </tr>
    <tr>
        <td>1,001</td>
        <td>Lorem</td>
    </tr>
    <tr>
        <td>1,001</td>
        <td>Lorem</td>
    </tr><tr>
        <td>1,001</td>
        <td>Lorem</td>
    </tr>
    <tr>
        <td>1,001</td>
        <td>Lorem</td>
    </tr>
    <tr>
        <td>1,001</td>
        <td>Lorem</td>
    </tr>
</tbody>
</table>
`