export const table1 = document.createElement('div');
table1.className = 'table-responsive table1';
table1.innerHTML = `
<table class="table table-striped table-sm table1">
    <thead>
        <tr>
        <th>#</th>
        <th>Header</th>
        <th>Header</th>
        </tr>
    </thead>
    <tbody>
        <tr>
        <td>1,001</td>
        <td>Lorem</td>
        <td>ipsum</td>
        </tr>
        <tr>
        <td>1,002</td>
        <td>amet</td>
        <td>consectetur</td>
        </tr>
        <tr>
        <td>1,003</td>
        <td>Integer</td>
        <td>nec</td>
        </tr>
        <tr>
        <td>1,003</td>
        <td>libero</td>
        <td>Sed</td>
        </tr>
        <tr>
        <td>1,002</td>
        <td>amet</td>
        <td>consectetur</td>
        </tr>
        <tr>
        <td>1,003</td>
        <td>Integer</td>
        <td>nec</td>
        </tr>
        <tr>
        <td>1,003</td>
        <td>libero</td>
        <td>Sed</td>
        </tr>
        <tr>
        <td>1,001</td>
        <td>Lorem</td>
        <td>ipsum</td>
        </tr>
        <tr>
        <td>1,002</td>
        <td>amet</td>
        <td>consectetur</td>
        </tr>
        <tr>
        <td>1,003</td>
        <td>Integer</td>
        <td>nec</td>
        </tr>
        <tr>
        <td>1,003</td>
        <td>libero</td>
        <td>Sed</td>
        </tr>
    </tbody>
    </table>
`